"""Remediation demo: write redacted copies of the highest-risk documents.

Uses presidio-anonymizer's "replace" operator so every detected value
becomes a tag such as ``<IN_AADHAAR>``. Only DATE_TIME is left readable
(redacting every date makes letters unreadable); LOCATION is redacted because
spaCy sometimes labels a person's name as a place.
The redacted copies are written as .txt files to output/redacted/.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List

from presidio_anonymizer import AnonymizerEngine
from presidio_anonymizer.entities import OperatorConfig, RecognizerResult

from . import get_logger, load_config

log = get_logger("redact")


def redact_text(text: str, findings: List[Dict[str, Any]], skip_entities: set) -> str:
    """Replace each finding in ``text`` with ``<ENTITY_TYPE>``."""
    results = [RecognizerResult(entity_type=f["entity_type"], start=f["start"], end=f["end"], score=f["confidence"])
               for f in findings if f["entity_type"] not in skip_entities]
    if not results:
        return text
    engine = AnonymizerEngine()
    operators = {"DEFAULT": OperatorConfig("replace")}  # default replacement is "<ENTITY_TYPE>"
    return engine.anonymize(text=text, analyzer_results=results, operators=operators).text


def _safe_name(path: str) -> str:
    stem = Path(path).name
    return re.sub(r"[^A-Za-z0-9._-]+", "_", stem)[:80]


def redact_top_documents(documents: List[Dict[str, Any]], texts: Dict[str, str],
                         findings_by_doc: Dict[str, List[Dict[str, Any]]], out_dir: Path,
                         top_n: int | None = None) -> List[Dict[str, str]]:
    """Redact the ``top_n`` highest-risk documents; returns [{doc_id, source, redacted_path}]."""
    cfg = load_config()
    top_n = top_n or cfg["remediation"]["top_redacted_docs"]
    skip = {"DATE_TIME"}  # dates stay readable; everything else (including LOCATION) is redacted
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.redacted.txt"):  # keep only the latest scan's samples
        old.unlink()

    ranked = sorted((d for d in documents if d["risk_level"] != "Clean"),
                    key=lambda d: d["risk_score"], reverse=True)[:top_n]
    written = []
    for rank, doc in enumerate(ranked, start=1):
        redacted = redact_text(texts.get(doc["doc_id"], ""), findings_by_doc.get(doc["doc_id"], []), skip)
        target = out_dir / f"{rank:02d}_{_safe_name(doc['path'])}.redacted.txt"
        header = (f"# REDACTED COPY - generated by PII Risk Dashboard\n"
                  f"# Source: {Path(doc['path']).name}\n"
                  f"# Risk: {doc['risk_level']} ({doc['risk_score']}) - {doc['reason']}\n\n")
        target.write_text(header + redacted, encoding="utf-8")
        written.append({"doc_id": doc["doc_id"], "source": doc["path"], "redacted_path": str(target)})
    log.info("Wrote %d redacted samples to %s", len(written), out_dir)
    return written
